### ISSUE TITLE
Requesting library in Swift code!!!

### ISSUE THREAD

**Issue by boominadhaprakash** [dagostini/DAMapAnnotation#2]
Hi,

I have tested the library. It is working fine. 

It would be great if this library is also available in Swift code.

Thanks :)

**Comment by dagostini** [comment]
Hi,

to call it a library would be a bit much, it's a simple class that's doing most of the work :)

I could easily convert it to swift for you, I'm busy atm, maybe over the weekend.

Have a nice day :)
Dejan.

**Comment by boominadhaprakash** [comment]
Hi Dejan,

Thank you :)

**Comment by dagostini** [comment]
Hi,

I converted the main view into swift, check it out. You should be able to drag & drop DAMapAnnotationView.swift and DAMapAnnotationView.xib into your project and use it as is.

Let me know if it works for you.

Have a nice day :)
Dejan.

**Comment by boominadhaprakash** [comment]
Hi Dejan,

Thank you so much. Let you know if it works :)

**Comment by boominadhaprakash** [comment]
Dejan,

I have imported that .swift file and .xib file as you said. But I am facing problem in converting the DAMapViewController.m file objective c code to Swift code. Especially that removePlacesFromMap and loadPlacesOnMap functions. 

I am using the removePlacesFromMap function like this.

```
func removePlacesFromMap()
    {
        self.gmapview.selectedMarker = nil

        for place:GMSMarker in self.markersArray
        {
            place.map = nil
            place.panoramaView = nil
        }
    }
```

But I am getting error in for loop. Please see the image in this link [click here](https://drive.google.com/open?id=0B9nDm4Bqrnh-cGIyaGpFUksweW8)

Can you please help me on that.

Thanks,
Boominadha Prakash M

**Comment by boominadhaprakash** [comment]
Hi Dejan,

I have fixed that issue. Now Marker is displaying with info window. Thanks for your help. 
Can you please tell is it possible to display the info window below the marker icon? If possible means please tell me where to change the code.
I have tried lot in DAMapAnnotationView.swift file. But couldn't achieve the expected result.

Thanks,
Boominadha Prakash M

**Comment by boominadhaprakash** [comment]
Hi Dejan,

I fixed that issue also. Now all infowindows are displaying below the maker.

Thanks to you for changed the class file to Swift code. It has really helped me lot :)

Thanks,
Boominadha Prakash M

**Comment by dagostini** [comment]
You're welcome. Sorry for my late reply, I was on a vacation :)
