### ISSUE TITLE
Resizing the annotation image based on device

### ISSUE THREAD

**Issue by kishykumar** [dagostini/DAMapAnnotation#3]
Hi, 

I noticed that the 'annotation image with marker' resizes with device in your sample app. That is, appears small on iPhone 5, bigger on iPhone 6. 

But, when I run it with my code, it doesn't resize. 

Can you please explain if anything needs to be done for adjusting the size of marker+annotation image based on device?

**Comment by dagostini** [comment]
Hi,

I'm not sure I understand. Can you please post some images of your problem? I was testing it on the simulator, and it appears the same size (as it should).

The markers should be the same size on any device.
